### PR TITLE
feat(rdkafka-sys): update librdkafka to v2.1.1

### PR DESCRIPTION
**Pull request by wmorgan6796**
Updating librdkafka to latest release. This also allows for usage of openssl 3.0, but upgrading openssl-sys felt like outside the scope of this PR.

### CODE REVIEW

**Comment by wmorgan6796** [comment]
@davidblewett is this something that could get some eyes? The version of librdkafka is a bit old and updating would help the library I think.

**Comment by davidblewett** [comment]
@wmorgan6796 we are interested in updated librdkafka soon, yes. We were waiting on https://github.com/confluentinc/librdkafka/pull/4171 to be included in a release first and updating to that.

**Comment by mensfeld** [comment]
@davidblewett yeah since you're going for 2.1.1 you may as well wait for 2.2.0 ;)

FYI I have an extensive integration suite for librdkafka, so you can also watch the issue you mentioned for updates. Once I run them and stable I will close this issue.

**Comment by mensfeld** [comment]
@abrisco just the discussion: https://github.com/confluentinc/librdkafka/discussions/4314

**Comment by jaudiger** [comment]
The version 2.2.0 has been released yesterday: https://github.com/confluentinc/librdkafka/releases/tag/v2.2.0 :star:

**Comment by mensfeld** [comment]
@jaudiger and it is stable. I can no longer reproduce this on my side in Ruby.

**Comment by mensfeld** [comment]
@jaudiger nvmd I still see it :cry:  and I can reproduce it with 2.2.0

**Comment by rukai** [comment]
Hi, just popping into mention that I've been waiting for this to land and i'm hoping we can go ahead with a release containing 2.1.1 or 2.2.0

**Comment by dertin** [comment]
Hi, Is there any insight available regarding the timeline for the release of this upgrade ? Are there any challenges that could potentially impact the advancement of this initiative?

**Comment by mensfeld** [comment]
@dertin 2.2.0 does not fully fix this. A more complex fix or rather mitigation with rebalance state tracking is needed.  @davidblewett feel free to ping me for a more extensive explanation if you need.

**Comment by davidblewett** [comment]
@mensfeld I recall seeing some updates from you along those lines. Can you point me to what is needed to implement the mitigation? I'm not sure I will have the cycles to implement it, but it will help move the ball forward.

**Comment by davidblewett** [comment]
Close this in favor of updating to v2.2.0: https://github.com/fede1024/rust-rdkafka/pull/603 .

**Pull request closed without merging**
