### PR TITLE
Change docker compose env vars to be strings, which is what they are

### LINKED ISSUE #242: Tests are failing in master
1. `docker-compose up`
 2. cargo test

Tail of the output:

```
     Running target/debug/deps/test_admin-1ef772f4dd6d6f35

running 4 tests
test test_event_errors ... ok
test utils::tests::test_populate_topic ... ok
test test_topics ... FAILED
test test_configs ... test test_configs has been running for over 60 seconds
test test_configs ... FAILED

failures:

---- test_topics stdout ----
thread 'test_topics' panicked at 'assertion failed: `(left == right)`
  left: `[Ok("__test_fClx63mB75"), Err(("__test_qD4Bu8AGac", RequestTimedOut))]`,
 right: `[Ok("__test_fClx63mB75"), Ok("__test_qD4Bu8AGac")]`', tests/test_admin.rs:105:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- test_configs stdout ----
thread 'test_configs' panicked at 'describe configs failed: KafkaError (Admin operation error: OperationTimedOut (Local: Timed out))', tests/test_admin.rs:311:15


failures:
    test_configs
    test_topics

test result: FAILED. 2 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out
```

Following topic always fails to create:

```
        let topic2 = NewTopic {
            name: &name2,
            num_partitions: 3,
            replication: TopicReplication::Variable(&[&[0], &[0], &[0]]),
            config: Vec::new(),
        };
```

<details>
<summary>Kafka log for a single invocaton of `test_topics`</summary>

```
[2020-05-09 12:16:47,226] INFO Creating topic __test_XYCbpiOkzN with configuration {max.message.bytes=1234} and initial partition assignment Map(0 -> ArrayBuffer(1001)) (kafka.zk.AdminZkClient)
[2020-05-09 12:16:47,281] INFO [Controller id=1001] New topics: [Set(__test_XYCbpiOkzN)], deleted topics: [Set()], new partition replica assignment [Map(__test_XYCbpiOkzN-0 -> Vector(1001))] (kafka.controller.KafkaController)
[2020-05-09 12:16:47,282] INFO [Controller id=1001] New partition creation callback for __test_XYCbpiOkzN-0 (kafka.controller.KafkaController)
[2020-05-09 12:16:47,285] TRACE [Controller id=1001 epoch=1] Changed partition __test_XYCbpiOkzN-0 state from NonExistentPartition to NewPartition with assigned replicas 1001 (state.change.logger)
[2020-05-09 12:16:47,288] TRACE [Controller id=1001 epoch=1] Changed state of replica 1001 for partition __test_XYCbpiOkzN-0 from NonExistentReplica to NewReplica (state.change.logger)
[2020-05-09 12:16:47,295] INFO Creating topic __test_rROC3KJfcB with configuration {} and initial partition assignment Map(2 -> ArrayBuffer(0), 1 -> ArrayBuffer(0), 0 -> ArrayBuffer(0)) (kafka.zk.AdminZkClient)
[2020-05-09 12:16:47,363] TRACE [Controller id=1001 epoch=1] Changed partition __test_XYCbpiOkzN-0 from NewPartition to OnlinePartition with state LeaderAndIsr(leader=1001, leaderEpoch=0, isr=List(1001), zkVersion=0) (state.change.logger)
[2020-05-09 12:16:47,384] TRACE [Controller id=1001 epoch=1] Sending become-leader LeaderAndIsr request PartitionState(controllerEpoch=1, leader=1001, leaderEpoch=0, isr=1001, zkVersion=0, replicas=1001, isNew=true) to broker 1001 for partition __test_XYCbpiOkzN-0 (state.change.logger)
[2020-05-09 12:16:47,385] TRACE [Controller id=1001 epoch=1] Sending UpdateMetadata request PartitionState(controllerEpoch=1, leader=1001, leaderEpoch=0, isr=[1001], zkVersion=0, replicas=[1001], offlineReplicas=[]) to brokers Set(1001) for partition __test_XYCbpiOkzN-0 (state.change.logger)
[2020-05-09 12:16:47,386] TRACE [Controller id=1001 epoch=1] Changed state of replica 1001 for partition __test_XYCbpiOkzN-0 from NewReplica to OnlineReplica (state.change.logger)
[2020-05-09 12:16:47,386] TRACE [Broker id=1001] Received LeaderAndIsr request PartitionState(controllerEpoch=1, leader=1001, leaderEpoch=0, isr=1001, zkVersion=0, replicas=1001, isNew=true) correlation id 21 from controller 1001 epoch 1 for partition __test_XYCbpiOkzN-0 (state.change.logger)
[2020-05-09 12:16:47,393] TRACE [Broker id=1001] Handling LeaderAndIsr request correlationId 21 from controller 1001 epoch 1 starting the become-leader transition for partition __test_XYCbpiOkzN-0 (state.change.logger)
[2020-05-09 12:16:47,394] INFO [ReplicaFetcherManager on broker 1001] Removed fetcher for partitions Set(__test_XYCbpiOkzN-0) (kafka.server.ReplicaFetcherManager)
[2020-05-09 12:16:47,395] INFO [Controller id=1001] New topics: [Set(__test_rROC3KJfcB)], deleted topics: [Set()], new partition replica assignment [Map(__test_rROC3KJfcB-2 -> Vector(0), __test_rROC3KJfcB-1 -> Vector(0), __test_rROC3KJfcB-0 -> Vector(0))] (kafka.controller.KafkaController)
[2020-05-09 12:16:47,395] INFO [Controller id=1001] New partition creation callback for __test_rROC3KJfcB-2,__test_rROC3KJfcB-1,__test_rROC3KJfcB-0 (kafka.controller.KafkaController)
[2020-05-09 12:16:47,395] TRACE [Controller id=1001 epoch=1] Changed partition __test_rROC3KJfcB-2 state from NonExistentPartition to NewPartition with assigned replicas 0 (state.change.logger)
[2020-05-09 12:16:47,395] TRACE [Controller id=1001 epoch=1] Changed partition __test_rROC3KJfcB-1 state from NonExistentPartition to NewPartition with assigned replicas 0 (state.change.logger)
[2020-05-09 12:16:47,395] TRACE [Controller id=1001 epoch=1] Changed partition __test_rROC3KJfcB-0 state from NonExistentPartition to NewPartition with assigned replicas 0 (state.change.logger)
[2020-05-09 12:16:47,395] TRACE [Controller id=1001 epoch=1] Changed state of replica 0 for partition __test_rROC3KJfcB-2 from NonExistentReplica to NewReplica (state.change.logger)
[2020-05-09 12:16:47,395] TRACE [Controller id=1001 epoch=1] Changed state of replica 0 for partition __test_rROC3KJfcB-1 from NonExistentReplica to NewReplica (state.change.logger)
[2020-05-09 12:16:47,395] TRACE [Controller id=1001 epoch=1] Changed state of replica 0 for partition __test_rROC3KJfcB-0 from NonExistentReplica to NewReplica (state.change.logger)
[2020-05-09 12:16:47,396] ERROR [Controller id=1001 epoch=1] Controller 1001 epoch 1 failed to change state for partition __test_rROC3KJfcB-2 from NewPartition to OnlinePartition (state.change.logger)
kafka.common.StateChangeFailedException: Controller 1001 epoch 1 encountered error during state change of partition __test_rROC3KJfcB-2 from New to Online, assigned replicas are [], live brokers are [Set(1001)]. No assigned replica is alive.
	at kafka.controller.ZkPartitionStateMachine.$anonfun$initializeLeaderAndIsrForPartitions$5(PartitionStateMachine.scala:259)
	at kafka.controller.ZkPartitionStateMachine.$anonfun$initializeLeaderAndIsrForPartitions$5$adapted(PartitionStateMachine.scala:254)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at kafka.controller.ZkPartitionStateMachine.initializeLeaderAndIsrForPartitions(PartitionStateMachine.scala:254)
	at kafka.controller.ZkPartitionStateMachine.doHandleStateChanges(PartitionStateMachine.scala:207)
	at kafka.controller.ZkPartitionStateMachine.handleStateChanges(PartitionStateMachine.scala:145)
	at kafka.controller.KafkaController.onNewPartitionCreation(KafkaController.scala:490)
	at kafka.controller.KafkaController.processTopicChange(KafkaController.scala:1319)
	at kafka.controller.KafkaController.process(KafkaController.scala:1590)
	at kafka.controller.QueuedEvent.process(ControllerEventManager.scala:53)
	at kafka.controller.ControllerEventManager$ControllerEventThread.$anonfun$doWork$1(ControllerEventManager.scala:137)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:31)
	at kafka.controller.ControllerEventManager$ControllerEventThread.doWork(ControllerEventManager.scala:137)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2020-05-09 12:16:47,396] ERROR [Controller id=1001 epoch=1] Controller 1001 epoch 1 failed to change state for partition __test_rROC3KJfcB-1 from NewPartition to OnlinePartition (state.change.logger)
kafka.common.StateChangeFailedException: Controller 1001 epoch 1 encountered error during state change of partition __test_rROC3KJfcB-1 from New to Online, assigned replicas are [], live brokers are [Set(1001)]. No assigned replica is alive.
	at kafka.controller.ZkPartitionStateMachine.$anonfun$initializeLeaderAndIsrForPartitions$5(PartitionStateMachine.scala:259)
	at kafka.controller.ZkPartitionStateMachine.$anonfun$initializeLeaderAndIsrForPartitions$5$adapted(PartitionStateMachine.scala:254)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at kafka.controller.ZkPartitionStateMachine.initializeLeaderAndIsrForPartitions(PartitionStateMachine.scala:254)
	at kafka.controller.ZkPartitionStateMachine.doHandleStateChanges(PartitionStateMachine.scala:207)
	at kafka.controller.ZkPartitionStateMachine.handleStateChanges(PartitionStateMachine.scala:145)
	at kafka.controller.KafkaController.onNewPartitionCreation(KafkaController.scala:490)
	at kafka.controller.KafkaController.processTopicChange(KafkaController.scala:1319)
	at kafka.controller.KafkaController.process(KafkaController.scala:1590)
	at kafka.controller.QueuedEvent.process(ControllerEventManager.scala:53)
	at kafka.controller.ControllerEventManager$ControllerEventThread.$anonfun$doWork$1(ControllerEventManager.scala:137)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:31)
	at kafka.controller.ControllerEventManager$ControllerEventThread.doWork(ControllerEventManager.scala:137)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2020-05-09 12:16:47,396] ERROR [Controller id=1001 epoch=1] Controller 1001 epoch 1 failed to change state for partition __test_rROC3KJfcB-0 from NewPartition to OnlinePartition (state.change.logger)
kafka.common.StateChangeFailedException: Controller 1001 epoch 1 encountered error during state change of partition __test_rROC3KJfcB-0 from New to Online, assigned replicas are [], live brokers are [Set(1001)]. No assigned replica is alive.
	at kafka.controller.ZkPartitionStateMachine.$anonfun$initializeLeaderAndIsrForPartitions$5(PartitionStateMachine.scala:259)
	at kafka.controller.ZkPartitionStateMachine.$anonfun$initializeLeaderAndIsrForPartitions$5$adapted(PartitionStateMachine.scala:254)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at kafka.controller.ZkPartitionStateMachine.initializeLeaderAndIsrForPartitions(PartitionStateMachine.scala:254)
	at kafka.controller.ZkPartitionStateMachine.doHandleStateChanges(PartitionStateMachine.scala:207)
	at kafka.controller.ZkPartitionStateMachine.handleStateChanges(PartitionStateMachine.scala:145)
	at kafka.controller.KafkaController.onNewPartitionCreation(KafkaController.scala:490)
	at kafka.controller.KafkaController.processTopicChange(KafkaController.scala:1319)
	at kafka.controller.KafkaController.process(KafkaController.scala:1590)
	at kafka.controller.QueuedEvent.process(ControllerEventManager.scala:53)
	at kafka.controller.ControllerEventManager$ControllerEventThread.$anonfun$doWork$1(ControllerEventManager.scala:137)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:31)
	at kafka.controller.ControllerEventManager$ControllerEventThread.doWork(ControllerEventManager.scala:137)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:89)
[2020-05-09 12:16:47,397] TRACE [Controller id=1001 epoch=1] Changed state of replica 0 for partition __test_rROC3KJfcB-2 from NewReplica to OnlineReplica (state.change.logger)
[2020-05-09 12:16:47,397] TRACE [Controller id=1001 epoch=1] Changed state of replica 0 for partition __test_rROC3KJfcB-1 from NewReplica to OnlineReplica (state.change.logger)
[2020-05-09 12:16:47,397] TRACE [Controller id=1001 epoch=1] Changed state of replica 0 for partition __test_rROC3KJfcB-0 from NewReplica to OnlineReplica (state.change.logger)
[2020-05-09 12:16:47,405] INFO [Log partition=__test_XYCbpiOkzN-0, dir=/var/lib/kafka/data] Loading producer state till offset 0 with message format version 2 (kafka.log.Log)
[2020-05-09 12:16:47,407] INFO [Log partition=__test_XYCbpiOkzN-0, dir=/var/lib/kafka/data] Completed load of log with 1 segments, log start offset 0 and log end offset 0 in 10 ms (kafka.log.Log)
[2020-05-09 12:16:47,418] INFO Created log for partition __test_XYCbpiOkzN-0 in /var/lib/kafka/data with properties {compression.type -> producer, message.downconversion.enable -> true, min.insync.replicas -> 1, segment.jitter.ms -> 0, cleanup.policy -> [delete], flush.ms -> 9223372036854775807, segment.bytes -> 1073741824, retention.ms -> 604800000, flush.messages -> 9223372036854775807, message.format.version -> 2.3-IV1, file.delete.delay.ms -> 60000, max.compaction.lag.ms -> 9223372036854775807, max.message.bytes -> 1234, min.compaction.lag.ms -> 0, message.timestamp.type -> CreateTime, preallocate -> false, min.cleanable.dirty.ratio -> 0.5, index.interval.bytes -> 4096, unclean.leader.election.enable -> false, retention.bytes -> -1, delete.retention.ms -> 86400000, segment.ms -> 604800000, message.timestamp.difference.max.ms -> 9223372036854775807, segment.index.bytes -> 10485760}. (kafka.log.LogManager)
[2020-05-09 12:16:47,420] INFO [Partition __test_XYCbpiOkzN-0 broker=1001] No checkpointed highwatermark is found for partition __test_XYCbpiOkzN-0 (kafka.cluster.Partition)
[2020-05-09 12:16:47,420] INFO Replica loaded for partition __test_XYCbpiOkzN-0 with initial high watermark 0 (kafka.cluster.Replica)
[2020-05-09 12:16:47,420] INFO [Partition __test_XYCbpiOkzN-0 broker=1001] __test_XYCbpiOkzN-0 starts at Leader Epoch 0 from offset 0. Previous Leader Epoch was: -1 (kafka.cluster.Partition)
[2020-05-09 12:16:47,437] TRACE [Broker id=1001] Stopped fetchers as part of become-leader request from controller 1001 epoch 1 with correlation id 21 for partition __test_XYCbpiOkzN-0 (last update controller epoch 1) (state.change.logger)
[2020-05-09 12:16:47,437] TRACE [Broker id=1001] Completed LeaderAndIsr request correlationId 21 from controller 1001 epoch 1 for the become-leader transition for partition __test_XYCbpiOkzN-0 (state.change.logger)
[2020-05-09 12:16:47,438] TRACE [Controller id=1001 epoch=1] Received response {error_code=0,partitions=[{topic=__test_XYCbpiOkzN,partition=0,error_code=0}]} for request LEADER_AND_ISR with correlation id 21 sent to broker localhost:9092 (id: 1001 rack: null) (state.change.logger)
[2020-05-09 12:16:47,442] TRACE [Broker id=1001] Cached leader info PartitionState(controllerEpoch=1, leader=1001, leaderEpoch=0, isr=[1001], zkVersion=0, replicas=[1001], offlineReplicas=[]) for partition __test_XYCbpiOkzN-0 in response to UpdateMetadata request sent by controller 1001 epoch 1 with correlation id 22 (state.change.logger)
[2020-05-09 12:16:47,443] TRACE [Controller id=1001 epoch=1] Received response {error_code=0} for request UPDATE_METADATA with correlation id 22 sent to broker localhost:9092 (id: 1001 rack: null) (state.change.logger)
[2020-05-09 12:17:25,634] INFO [Controller id=1001] Processing automatic preferred replica leader election (kafka.controller.KafkaController)
[2020-05-09 12:17:25,634] TRACE [Controller id=1001] Checking need to trigger auto leader balancing (kafka.controller.KafkaController)
[2020-05-09 12:17:25,638] DEBUG [Controller id=1001] Preferred replicas by broker Map(1001 -> Map(__test_G5MyWZaB7H-0 -> Vector(1001), __test_IvXK07Ghdg-0 -> Vector(1001), __test_QYJR1r3BKI-0 -> Vector(1001), __test_fa4XzGKU8b-2 -> Vector(1001), __test_fa4XzGKU8b-0 -> Vector(1001), __test_9o0CvUNc4L-2 -> Vector(1001), __test_WP7w8KQkAT-0 -> Vector(1001), __confluent.support.metrics-0 -> Vector(1001), __test_9o0CvUNc4L-1 -> Vector(1001), __test_XYCbpiOkzN-0 -> Vector(1001), __test_fa4XzGKU8b-1 -> Vector(1001), __test_fClx63mB75-0 -> Vector(1001), __test_9o0CvUNc4L-0 -> Vector(1001), __test_WkpjI3K0CF-0 -> Vector(1001), __test_ZxbdQyPVDT-0 -> Vector(1001), __test_sdO0O7XE0Y-0 -> Vector(1001), __test_ZtzHheCrHn-0 -> Vector(1001)), 0 -> Map(__test_cicWhR7HBN-0 -> Vector(0), __test_qD4Bu8AGac-0 -> Vector(0), __test_VNYFuSOty7-2 -> Vector(0), __test_hFIngEOunu-2 -> Vector(0), __test_YaXNlVuNOo-1 -> Vector(0), __test_hFIngEOunu-1 -> Vector(0), __test_NDbdthDjRQ-0 -> Vector(0), __test_VNYFuSOty7-0 -> Vector(0), __test_NJSj4TOrS7-0 -> Vector(0), __test_cicWhR7HBN-1 -> Vector(0), __test_6kHHZt3D4W-2 -> Vector(0), __test_6kHHZt3D4W-1 -> Vector(0), __test_cicWhR7HBN-2 -> Vector(0), __test_VNYFuSOty7-1 -> Vector(0), __test_NDbdthDjRQ-1 -> Vector(0), __test_NDbdthDjRQ-2 -> Vector(0), __test_rROC3KJfcB-1 -> Vector(0), __test_4hWgJohfhP-0 -> Vector(0), __test_rROC3KJfcB-2 -> Vector(0), __test_hFIngEOunu-0 -> Vector(0), __test_4hWgJohfhP-1 -> Vector(0), __test_NJSj4TOrS7-1 -> Vector(0), __test_6kHHZt3D4W-0 -> Vector(0), __test_YaXNlVuNOo-0 -> Vector(0), __test_qD4Bu8AGac-1 -> Vector(0), __test_NJSj4TOrS7-2 -> Vector(0), __test_qD4Bu8AGac-2 -> Vector(0), __test_4hWgJohfhP-2 -> Vector(0), __test_YaXNlVuNOo-2 -> Vector(0), __test_rROC3KJfcB-0 -> Vector(0))) (kafka.controller.KafkaController)
[2020-05-09 12:17:25,638] DEBUG [Controller id=1001] Topics not in preferred replica for broker 1001 Map() (kafka.controller.KafkaController)
[2020-05-09 12:17:25,638] TRACE [Controller id=1001] Leader imbalance ratio for broker 1001 is 0.0 (kafka.controller.KafkaController)
[2020-05-09 12:17:25,638] DEBUG [Controller id=1001] Topics not in preferred replica for broker 0 Map() (kafka.controller.KafkaController)
[2020-05-09 12:17:25,638] TRACE [Controller id=1001] Leader imbalance ratio for broker 0 is 0.0 (kafka.controller.KafkaController)
[2020-05-09 12:22:20,361] INFO [GroupMetadataManager brokerId=1001] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2020-05-09 12:22:25,722] INFO [Controller id=1001] Processing automatic preferred replica leader election (kafka.controller.KafkaController)
[2020-05-09 12:22:25,722] TRACE [Controller id=1001] Checking need to trigger auto leader balancing (kafka.controller.KafkaController)
[2020-05-09 12:22:25,725] DEBUG [Controller id=1001] Preferred replicas by broker Map(1001 -> Map(__test_G5MyWZaB7H-0 -> Vector(1001), __test_IvXK07Ghdg-0 -> Vector(1001), __test_QYJR1r3BKI-0 -> Vector(1001), __test_fa4XzGKU8b-2 -> Vector(1001), __test_fa4XzGKU8b-0 -> Vector(1001), __test_9o0CvUNc4L-2 -> Vector(1001), __test_WP7w8KQkAT-0 -> Vector(1001), __confluent.support.metrics-0 -> Vector(1001), __test_9o0CvUNc4L-1 -> Vector(1001), __test_XYCbpiOkzN-0 -> Vector(1001), __test_fa4XzGKU8b-1 -> Vector(1001), __test_fClx63mB75-0 -> Vector(1001), __test_9o0CvUNc4L-0 -> Vector(1001), __test_WkpjI3K0CF-0 -> Vector(1001), __test_ZxbdQyPVDT-0 -> Vector(1001), __test_sdO0O7XE0Y-0 -> Vector(1001), __test_ZtzHheCrHn-0 -> Vector(1001)), 0 -> Map(__test_cicWhR7HBN-0 -> Vector(0), __test_qD4Bu8AGac-0 -> Vector(0), __test_VNYFuSOty7-2 -> Vector(0), __test_hFIngEOunu-2 -> Vector(0), __test_YaXNlVuNOo-1 -> Vector(0), __test_hFIngEOunu-1 -> Vector(0), __test_NDbdthDjRQ-0 -> Vector(0), __test_VNYFuSOty7-0 -> Vector(0), __test_NJSj4TOrS7-0 -> Vector(0), __test_cicWhR7HBN-1 -> Vector(0), __test_6kHHZt3D4W-2 -> Vector(0), __test_6kHHZt3D4W-1 -> Vector(0), __test_cicWhR7HBN-2 -> Vector(0), __test_VNYFuSOty7-1 -> Vector(0), __test_NDbdthDjRQ-1 -> Vector(0), __test_NDbdthDjRQ-2 -> Vector(0), __test_rROC3KJfcB-1 -> Vector(0), __test_4hWgJohfhP-0 -> Vector(0), __test_rROC3KJfcB-2 -> Vector(0), __test_hFIngEOunu-0 -> Vector(0), __test_4hWgJohfhP-1 -> Vector(0), __test_NJSj4TOrS7-1 -> Vector(0), __test_6kHHZt3D4W-0 -> Vector(0), __test_YaXNlVuNOo-0 -> Vector(0), __test_qD4Bu8AGac-1 -> Vector(0), __test_NJSj4TOrS7-2 -> Vector(0), __test_qD4Bu8AGac-2 -> Vector(0), __test_4hWgJohfhP-2 -> Vector(0), __test_YaXNlVuNOo-2 -> Vector(0), __test_rROC3KJfcB-0 -> Vector(0))) (kafka.controller.KafkaController)
[2020-05-09 12:22:25,725] DEBUG [Controller id=1001] Topics not in preferred replica for broker 1001 Map() (kafka.controller.KafkaController)
[2020-05-09 12:22:25,725] TRACE [Controller id=1001] Leader imbalance ratio for broker 1001 is 0.0 (kafka.controller.KafkaController)
[2020-05-09 12:22:25,725] DEBUG [Controller id=1001] Topics not in preferred replica for broker 0 Map() (kafka.controller.KafkaController)
[2020-05-09 12:22:25,726] TRACE [Controller id=1001] Leader imbalance ratio for broker 0 is 0.0 (kafka.controller.KafkaController)
```
</details>

### PR DESCRIPTION
**Pull request by redbaron**
Fixes #242 for me

### CODE REVIEW

**Comment by benesch** [comment]
Hi @redbaron, thanks for your interest. I'm not entirely sure we've gotten to the bottom of what the problem is, though. The existing Compose file works in CI, on my Mac, and on my Linux box. Perhaps there was something deeper that went wrong the first time you ran `docker-compose up` that resolved itself by the second time?

**Comment by benesch** [comment]
`docker-compose logs kafka` suggests that these environment variables are getting passed through just fine as is:

```
Attaching to rust-rdkafka_kafka_1
kafka_1      | ALLOW_UNSIGNED=false
kafka_1      | COMPONENT=kafka
kafka_1      | CONFLUENT_DEB_VERSION=1
kafka_1      | CONFLUENT_MAJOR_VERSION=5
kafka_1      | CONFLUENT_MINOR_VERSION=3
kafka_1      | CONFLUENT_MVN_LABEL=
kafka_1      | CONFLUENT_PATCH_VERSION=1
kafka_1      | CONFLUENT_PLATFORM_LABEL=
kafka_1      | CONFLUENT_SUPPORT_METRICS_ENABLE=0
kafka_1      | CONFLUENT_VERSION=5.3.1
kafka_1      | CUB_CLASSPATH=/etc/confluent/docker/docker-utils.jar
kafka_1      | HOME=/root
kafka_1      | HOSTNAME=d440e9dfeab4
kafka_1      | KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
kafka_1      | KAFKA_BROKER_ID=0
kafka_1      | KAFKA_NUM_PARTITIONS=3
kafka_1      | KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
kafka_1      | KAFKA_VERSION=5.3.1
kafka_1      | KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
kafka_1      | LANG=C.UTF-8
kafka_1      | PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
kafka_1      | PWD=/
kafka_1      | PYTHON_PIP_VERSION=8.1.2
kafka_1      | PYTHON_VERSION=2.7.9-1
kafka_1      | SCALA_VERSION=2.12
kafka_1      | SHLVL=1
kafka_1      | ZULU_OPENJDK_VERSION=8=8.38.0.13
```

```
Attaching to rust-rdkafka_zookeeper_1
zookeeper_1  | ===> ENV Variables ...
zookeeper_1  | ALLOW_UNSIGNED=false
zookeeper_1  | COMPONENT=zookeeper
zookeeper_1  | CONFLUENT_DEB_VERSION=1
zookeeper_1  | CONFLUENT_MAJOR_VERSION=5
zookeeper_1  | CONFLUENT_MINOR_VERSION=3
zookeeper_1  | CONFLUENT_MVN_LABEL=
zookeeper_1  | CONFLUENT_PATCH_VERSION=1
zookeeper_1  | CONFLUENT_PLATFORM_LABEL=
zookeeper_1  | CONFLUENT_VERSION=5.3.1
zookeeper_1  | CUB_CLASSPATH=/etc/confluent/docker/docker-utils.jar
zookeeper_1  | HOME=/root
zookeeper_1  | HOSTNAME=7338f74d826c
zookeeper_1  | KAFKA_VERSION=5.3.1
zookeeper_1  | LANG=C.UTF-8
zookeeper_1  | PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
zookeeper_1  | PWD=/
zookeeper_1  | PYTHON_PIP_VERSION=8.1.2
zookeeper_1  | PYTHON_VERSION=2.7.9-1
zookeeper_1  | SCALA_VERSION=2.12
zookeeper_1  | SHLVL=1
zookeeper_1  | ZOOKEEPER_CLIENT_PORT=2181
zookeeper_1  | ZULU_OPENJDK_VERSION=8=8.38.0.13
```

I'm fairly certain now that this is not related to the use of ints instead of strings, so I'm going to close this out. I suspect something else went wrong in #242, and I'm happy to dig in over there. For good measure, I'm using v1.25.0 of Docker Compose. If something is indeed broken in different versions of DC, I'm happy to reconsider this PR.

**Comment by redbaron** [comment]
@benesch ,
it turned out my docker-compose was a symlink  to `podman-compose`, which doesn't handle non-string values correctly. It is similar to how you need to quote 'true'` to prevent it from being interpreted as a boolean. 

 I verified env vars were indeed passed incorrectly before and incorrect treatment of "falsy" values like `0` (unquoted) was indeed the root cause.

This is a safe change, which doesn't break docker compose, please reconsider.

**Comment by benesch** [comment]
Thanks for digging in. I'm not in general excited about the idea of trying to maintain support for podman-compose, as it doesn't seem particularly complete at the moment: https://github.com/containers/podman-compose/issues/151. Symlinking `docker-compose` to `podman-compose` seems liable to cause you more headaches like this in the future.

**Comment by benesch** [comment]
I've reworked this slightly in #253 to use a syntax with which it is a bit harder to accidentally use a non-string. (You don't have to remember to quote values, specifically.) I believe this to be compatible with podman-compose which should fix your issue.

**Pull request closed without merging**
