### PR TITLE
Bump librdkafka to 0.9.3

### PR DESCRIPTION
**Pull request by thijsc**

### CODE REVIEW

**Comment by thijsc** [comment]
Anything holding this back?

**Comment by fede1024** [comment]
Just my lack of free time :)

Can you update the src/lib.rs file as well? I suggest always editing that one, and that run `python generate-readme.py > README.md` to generate the readme automatically.

**Comment by thijsc** [comment]
Done, will use the script next time.

**Comment by fede1024** [comment]
Thanks!

**Pull request merged**
