### PR TITLE
Freebsd support

### PR DESCRIPTION
**Pull request by AlexanderThaller**
I mostly copied stuff that applied for macos as the systems are pretty similar.

I also had to switch to gmake in the build.rs.

Its the first time I did something like this so probably some stuff can be improved but sofar it worked on my machine (`10.3-RELEASE FreeBSD 10.3-RELEASE`).

### CODE REVIEW

**Comment by AlexanderThaller** [comment]
I updated the bindings properly with bindgen.

**Comment by AlexanderThaller** [comment]
I see there is finally some more activity in this repository again. Is there something I can help with to get this merged or will you get to that eventually? It would really help to have this in the master branch/cargo crate.

**Comment by flavray** [comment]
Thanks for the PR and apologies for the delay.
Would you mind running `bindgen` once more (there have been some changes since August 2018)?

Going forward, I wonder how we could get updates to genrated FreeBSD bindings. I have access to both a linux and macos machines, but nothing running FreeBSD (yet?) and container support does not seem exist either. I guess that for now, having anyone using the library with FreeBSD open a PR is good-enough. Do you happen to have other ideas?

**Comment by AlexanderThaller** [comment]
Sure will run bindgen again and update the pull request.

I'm not sure how this could be done automatically in the future as CI integration systems usually don't support FreeBSD and would probably be the best way to do this.

I think that most rust libraries that have to do bindgen related stuff update it on demand (correct me if I'm wrong) so it should be fine. I would definitely open an issue/pull request again if something changes.

No worries about the delay I'm grateful that you took over the development of this library :D.

**Comment by AlexanderThaller** [comment]
I updated the bindings using bindgen 0.30.0 as written in the readme.

**Comment by AlexanderThaller** [comment]
Here is the output of `cargo test` against a local kafka broker `2.0.0`:

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.35s
     Running target/debug/deps/rdkafka-bf10568d72b3afcb

running 14 tests
test message::test::test_headers ... ok
test message::test::test_timestamp_conversion ... ok
test message::test::test_timestamp_creation ... ok
test client::tests::test_client ... ok
test topic_partition_list::tests::add_partition_offset_find ... ok
test producer::base_producer::tests::test_base_producer_clone ... ok
test topic_partition_list::tests::test_add_partition_offset_clone ... ok
test topic_partition_list::tests::add_partition_range ... ok
test util::tests::test_duration_to_millis ... ok
test topic_partition_list::tests::check_defaults ... ok
test topic_partition_list::tests::test_topic_map ... ok
test statistics::tests::test_statistics ... ok
test producer::future_producer::tests::test_future_producer_clone ... ok
test producer::future_producer::tests::test_base_future_topic_send_sync ... ok

test result: ok. 14 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/test_consumers-69cdbb1f655c3dc2

running 8 tests
Stats received: 1538 bytes
Stats received: 1517 bytes
Stats received: 1517 bytes
test test_produce_consume_base_assign ... ok
Stats received: 1517 bytes
test utils::tests::test_populate_topic ... ok
test test_produce_consume_iter ... ok
test test_produce_consume_base ... ok
test test_produce_consume_with_timestamp ... ok
Committing offsets: Ok(())
Stats received: 1517 bytes
Committing offsets: Ok(())
Committing offsets: Ok(())
Committing offsets: Ok(())
Committing offsets: Ok(())
Committing offsets: Ok(())
Committing offsets: Ok(())
Committing offsets: Ok(())
Committing offsets: Ok(())
Committing offsets: Ok(())
Committing offsets: Ok(())
Committing offsets: Ok(())
Stats received: 3522 bytes
Stats received: 3527 bytes
test test_consumer_commit_message ... ok
Stats received: 1517 bytes
test test_consumer_store_offset_commit ... ok
Stats received: 1517 bytes
Stats received: 1517 bytes
Stats received: 1517 bytes
Stats received: 1517 bytes
test test_consume_with_no_message_error ... ok

test result: ok. 8 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/test_high_producers-df9e0930c50580fc

running 1 test
test test_future_producer_send_fail ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/test_low_producers-c15f7b9d4fe527d1

running 5 tests
test test_base_producer_timeout ... ok
test test_base_producer_queue_full ... ok
test test_base_producer_headers ... ok
test test_threaded_producer_send ... ok
test utils::tests::test_populate_topic ... ok

test result: ok. 5 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/test_metadata-8210945a59dad653

running 4 tests
test utils::tests::test_populate_topic ... ok
test test_subscription ... ok
test test_metadata ... ok
test test_group_membership ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/utils-77369d1185aab2ba

running 1 test
test tests::test_populate_topic ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests rdkafka

running 6 tests
test src/consumer/base_consumer.rs - consumer::base_consumer::BaseConsumer<C>::iter (line 152) ... ok
test src/producer/base_producer.rs - producer::base_producer::BaseRecord (line 135) ... ok
test src/consumer/base_consumer.rs - consumer::base_consumer::BaseConsumer<C>::iter (line 129) ... ok
test src/producer/base_producer.rs - producer::base_producer::BaseRecord (line 123) ... ok
test src/consumer/base_consumer.rs - consumer::base_consumer::BaseConsumer<C>::iter (line 141) ... ok
test src/producer/base_producer.rs - producer::base_producer::BaseProducer (line 249) ... ok

test result: ok. 6 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

```

**Comment by flavray** [comment]
Thank you for contributing!

The failing tests on nightly are also failing on master, so not related to your changes :)

**Pull request merged**
