### PR TITLE
Add async split_partition_queue to StreamConsumer

### PR DESCRIPTION
**Pull request by nemosupremo**
I currently need a way to consume partitions concurrently in an asynchronous context. `BaseConsumer` currently provides `split_partition_queue` for "synchronous" polling, but `StreamConsumer` provides no function. I decided to take a stab at implementing it, as it seemed simple enough; however this PR is more in the design stage.

What I opted to do was "overload" `MessageStream` to simply rollover an enum of values, either a `StreamConsumer` or `Arc<BaseConsumer>` + `Partition`.  To achieve this I also had `StreamConsumer` always hold on to an `Arc` of BaseConsumer, which I think should have a very minimal cost compared to the owned version.

The only problem I see is that each `PartitionQueue` has its lifetime tied to the `StreamConsumer` despite each `PartitionQueue` holding an Arc to base consumer. I'm not sure yet if this is an onerous restriction, however an alternate design would require a new `MessageStream` type (which I think may duplicate more code), or allowing `MessageStream` to hold an Arc to `StreamConsumer` or making the implantation of `MessageStream` generic over the "consumer".

### CODE REVIEW

**Comment by nemosupremo** [comment]
Upon further research, it seems like for this to work there would need to be a type of `BorrowedMessage` that has a `'static` lifetime but also holds a reference to its consumer in an Arc.

**Comment by nemosupremo** [comment]
Now the only remaining problem is much of the `Consumer` API requires a `BorrowedMessage`. A path forward would be to change the api to accept something like `AsRef<BorrowedMessage>`

**Comment by nemosupremo** [comment]
One final change: I've opted to remove the boxing of `BaseConsumer` in `StreamConsumer`. It seemed silly to have the double Arc requirement.

**Comment by benesch** [comment]
Thanks very much for working on this, @nemosupremo! I'm sorry I haven't had a chance to look things over yet. Things are busy at work right now, and this partition queue stuff is really subtle. Definitely a useful change though. Hopefully have time for a proper review soon.

**Comment by benesch** [comment]
Sorry for the very long delay here. I put together a slightly different implementation in #411, but one that was very much based on this one! The big difference is a refactor that allowed the removal of the `MessageStreamConsumer` type.

**Comment by benesch** [comment]
Thanks again for the PR!

**Pull request closed without merging**
