### PR TITLE
Add producer transaction support

### PR DESCRIPTION
**Pull request by roignpar**
To do:
- [x] ThreadedProducer
- [ ] FutureProducer
- [x] [proper error handling](https://github.com/fede1024/rust-rdkafka/issues/289#issuecomment-677759157)
- [x] understand if it makes sense to serialize and deserialize consumer group metadata like other librdkafka wrappers do
- [x] documentation
- [x] tests

### CODE REVIEW

**Comment by roignpar** [comment]
Opened this PR following https://github.com/fede1024/rust-rdkafka/issues/289.

**Comment by roignpar** [comment]
@benesch any clue how to make the transaction methods `async` on the `FutureProducer`? librdkafka doesn't support callbacks for transaction operations.

**Comment by benesch** [comment]
Sorry, I've been swamped lately. About to head off on vacation, which means I should actually have a few spare hours to look at this. But I gave it a quick skim and everything looks very promising!

> @benesch any clue how to make the transaction methods async on the FutureProducer? librdkafka doesn't support callbacks for transaction operations.

Nope, afraid not. Maybe there are some tricks along the lines mentioned in #273, but any solution along those lines wouldn't be plug n play.

**Comment by roignpar** [comment]
Even with the event interface, there seem to be no transaction events defined in librdkafka.
I propose that as part of this PR the `FutureProducer` transaction methods be sync and an async API be implemented separately when it becomes feasible.
Since the methods are the same on all producer types and both `ThreadedProducer` and `FutureProducer` delegate to the base producer, would it make sense to create a `TransactionalProducer` trait similar to the `Consumer` trait?

**Comment by roignpar** [comment]
While writing the tests I ran into something that I was able to reproduce using the go librdkafka wrapper and opened an [issue](https://github.com/confluentinc/confluent-kafka-go/issues/525).
Added an example and more documentation.
Feel free to change anything!

**Comment by benesch** [comment]
Sorry for the massive delay here. I'm working through this today one commit at a time.

**Comment by damoon** [comment]
I am very new to Rust, but I would love to see exactly once semantics for Kafka.
Anything I can do to help?

**Comment by benesch** [comment]
Thanks very much for this. This was an absolutely awesome PR. I'm sorry that my review stalled out on this for so long. I took this and made a few changes in #323. The only real substantive change was fixing a few memory safety issues with `RDKafkaError`. 

By the way, there's now a `Producer` trait, to mirror the `Consumer` trait, so that's where I moved the transaction-related methods to. It's a shame that they're blocking methods on the `FutureProducer`, but there's not much we can do about that.

**Pull request closed without merging**
