### PR TITLE
feat: Add a recv method on StreamConsumer

### PR DESCRIPTION
**Pull request by Marwes**
The borrow required by `MessageStream` makes the API awkward in some
cases. With this addition it becomes possible to just pass around the
`StreamConsumer` instead and just call `recv` instead of going through
`MessageStream`

### CODE REVIEW

**Comment by Marwes** [comment]
ping

**Comment by Marwes** [comment]
pong

**Comment by benesch** [comment]
Thanks very much for this, and sorry for the delay. I made a bunch of breaking changes to the `StreamConsumer` API that made this easier for me to reason about in #315, then added this method under the name `next` rather than `recv` to mirror the name of the method in the de facto standard `StreamExt` trait.

**Comment by Marwes** [comment]
I actually explicitly changed from `next` to `recv` because it is close to it, but not actually `StreamExt::next`. `tokio` does the same for it's channels for instance https://docs.rs/tokio/1.0.1/tokio/sync/mpsc/struct.Receiver.html#method.recv

**Comment by benesch** [comment]
Ok, I'm convinced. Renamed to `recv`.

**Pull request closed without merging**
