### PR TITLE
chore: Use backon to replace backoff

### PR DESCRIPTION
**Pull request by Xuanwo**
Backoff has been unmaintained for a while, so this PR replaces backoff with backon.

Related to https://github.com/ihrwein/backoff/issues/66

### CODE REVIEW

**Comment by Xuanwo** [comment]
Hi, @benesch, would you like to take a look? Thanks!

**Comment by benesch** [comment]
Sorry, I’ve mostly retired from maintainership of this project due to time constraints. @davidblewett or @fede1024 may be able to take a look.

**Comment by Xuanwo** [comment]
Hi, @davidblewett. I've rebased with the upstream. Please take another look. Thanks for the review.

**Review by davidblewett — APPROVED** [review]
+1

**Pull request merged**
