### PR TITLE
Add admin API client

### LINKED ISSUE #92: Add admin client functions
The latest version of librdkafka supports the admin client. I wonder if it's a good idea to add support for it here, or put it in a separate project. Most of the time you will either consume/produce or use the admin client. But it might be useful for checking whether a topic is available and/or changing the configuration of a topic. https://github.com/edenhill/librdkafka/releases/tag/v0.11.5

### PR DESCRIPTION
**Pull request by benesch**
There's probably a few more bugs here to shake out, but this is mostly ready to go.

~This is based off of #119/#120. It's not technically tied to any of the changes in #119/#120, if for some reason we want to land this before those PRs.~

Fix #92.

### CODE REVIEW

**Comment by benesch** [comment]
Ok, fixed a few bugs and got tests passing. This is at least ready for review! (No rush! I realize this is quite a bit of code.)

**Comment by mahulst** [comment]
I've used this branch to create and delete topics, and it works like a charm. Except for testing, is there anything else I can do to help out and get this PR merged?

**Comment by Totoketchup** [comment]
This looks great and it would be useful. What is the status of this PR ?

**Comment by benesch** [comment]
We've been using this patch successfully at @MaterializeInc for a while now. It's waiting on a review from either @fede1024 or @flavray, both of whom I think have little time to dedicate to maintenance these days, unfortunately.

**Comment by fede1024** [comment]
Hi, thank you for contributing and sorry for the very very slow response time on our side. The change looks good. Would you mind resolving the configs?

**Comment by benesch** [comment]
It's quite alright, @fede1024! Thank you for finding the time. I've solved the rebase conflicts; hopefully should be good to go once CI passes.

**Comment by benesch** [comment]
Woohoo, it's green! The last commit is new, and it took a bit to figure out what was going on. Looks like we're now tickling a different code path inside librdkafka in test_metadata and getting metadata from bootstrap "broker" -1 instead of 0, which is perfectly valid and expected (see https://github.com/edenhill/librdkafka/commit/f50747e3bff53ee7021c3812a1b6b9b6635ea129).

**Comment by fede1024** [comment]
Great work, thank you!

**Pull request merged**
