### PR TITLE
Update librdkafka to 1.0.1

### LINKED ISSUE #132: Bump librdkafka to 1.0.1
It's out: https://github.com/edenhill/librdkafka/releases/tag/v1.0.1

### PR DESCRIPTION
**Pull request by thijsc**
Also update bindgen dependency to latest version. Fixes #132

### CODE REVIEW

**Comment by thijsc** [comment]
Anybody here?

**Comment by gklijs** [comment]
@flavray Can you take a look at some of the pr's and/or issues? Some are very small and would really help. If you don't have the time, maybe add more maintainers?

**Comment by gerred** [comment]
Hi @gklijs I'd be interested in helping to maintain this.

**Comment by gklijs** [comment]
@gerred that's nice to hear, but I can't help with that. I'm still in doubt if I want to become a maintainer.

**Pull request merged**
