### PR TITLE
Plumb message_queue_nonempty callback

### PR DESCRIPTION
**Pull request by benesch**
This makes it possible to receive a notification via a Rust callback when there are new messages available. The bulk of the implementation is in the last two commits; the first commit is just preparatory work.

### CODE REVIEW

**Comment by benesch** [comment]
@quodlibetor or @thijsc, can I talk one of you into reviewing this?

**Comment by thijsc** [comment]
Wouldn't it be possible to use a callback on the future? Or does that have downsides for you?

**Comment by benesch** [comment]
Yeah, at @MaterializeInc we're not using the futures consumer. We have our own event loop that calls `consumer.poll(0)` at regular intervals. When we don't receive any messages, we want to be able to put the thread with the event loop to sleep, but get woken up if a new message arrives, which this PR enables. (Without this PR, the only option is to create another thread that forwards received Kafka messages over a channel, which creates unnecessary overhead.)

**Comment by benesch** [comment]
Come to think of it, it should be possible to avoid the separate thread in the StreamConsumer entirely with the functionality in this PR. I'm going to poke at that a bit.

**Comment by thijsc** [comment]
This is blocked on getting the build green in #98.

**Comment by benesch** [comment]
>  I'm going to poke at that a bit.

This turns out to be fairly difficult, so I'm just going to merge as is, now that tests are passing. (Just needed to increase the timeout for CI, because things seem to be a bit slower due to the small Travis VMs.)

**Pull request merged**
