### PR TITLE
Convert unwraps to expects and test for custom product context

### PR DESCRIPTION
**Pull request by thijsc**
This converts some unwraps to expects so I could rule out some causes of a crash I'm seeing. It looks like the crash is caused by using a custom producer context, so I've added an integration test for this.

The test in this pull runs indefinitely. When you change line 54 back to this:

```rust
.create::<FutureProducer<_>>()
```

The test passes within a second or two again. Seems like something breaks when using `create_with_context` instead of `create`, so far I have no idea why. Any thoughts?

### CODE REVIEW

**Comment by fede1024** [comment]
Thanks! Because of a bug in the `delivery_cb` function, the context gets freed every time a message it receives. The `FutureProducerContext` is just a wrapper for a generic `ProducerContext`, normally empty, so there is no double free unless a custom context is specified.

I'm pushing the fix.

**Comment by fede1024** [comment]
Fix: https://github.com/fede1024/rust-rdkafka/commit/3a414227ae619954e1a07cf84107d9225a63222c

**Comment by fede1024** [comment]
The way the `FutureProducer` allows to specify a `ProducerContext` is very confusing at the moment, since the only method currently available in the trait is not actually executed (since it is used by the `FutureProducer` itself). I think we should remove this test, since it is a bit misleading.

I'll update the `FutureProducer` to use a different trait instead of `ProducerContext` (or nothing at all).

**Comment by thijsc** [comment]
Closing this one. I've cherry-picked the expect commit to #24 and opened #23 to track the producer context issue.

**Pull request closed without merging**
