### PR TITLE
Small suggestions

### PR DESCRIPTION
**Pull request by jaudiger**
Suggestions to resolve tiny issues.

### CODE REVIEW

**Comment by jaudiger** [comment]
Hi @benesch, I just ran the `cargo fmt --all` on my PR.. Sorry for that!

**Comment by benesch** [comment]
No problem!

**Comment by jaudiger** [comment]
This time with the anonymous lifetime :D I tested it in local, it builds, and the tests passed successfully. I wasn't aware about the usage of deny(rust_2018_idioms) in the compilation.

**Comment by jaudiger** [comment]
I’m not sure if the CI failures comes from my PR. I don’t understand why it passes successfully on some Kafka versions but not on another.

**Pull request closed without merging**
